apiVersion: v1
kind: Namespace
metadata:
  name: hotelup-cleaning
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotelup-cleaning-deployment
  labels:
    app: hotelup-cleaning
  namespace: hotelup-cleaning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotelup-cleaning
  template:
    metadata:
      name: hotelup-cleaning
      labels:
        app: hotelup-cleaning
    spec:
      containers:
        - name: hotelup-cleaning
          image: wiaz/hotelup.cleaning:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5004
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hotelup-cleaning-service
  labels:
    app: hotelup-cleaning
  namespace: hotelup-cleaning
spec:
    selector:
        app: hotelup-cleaning
    ports:
        - protocol: TCP
          port: 5004
          targetPort: 5004
    type: LoadBalancer
      