apiVersion: apps/v1
kind: Deployment
metadata:
    name: cleaning-deployment
    labels:
        app: hotelup
    namespace: hotelup
spec:
    replicas: 1
    selector:
        matchLabels:
            app: cleaning
    template:
        metadata:
            name: cleaning
            labels:
                app: cleaning
        spec:
            containers:
              - name: cleaning
                image: wiaz/hotelup.cleaning:latest
                imagePullPolicy: Always
                env:
                  - name: ASPNETCORE_ENVIRONMENT
                    value: Production
                ports:
                  - containerPort: 8080
                    protocol: TCP
            restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
    name: cleaning-service
    labels:
        app: cleaning
    namespace: hotelup
spec:
    selector:
        app: cleaning
    ports:
      - protocol: TCP
        port: 5004
        targetPort: 8080
    type: ClusterIP
